language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
os:
- linux
- osx
before_install:
- echo $LANG
- echo $LC_ALL
script:
- if [ $TRAVIS_OS_NAME == linux ]; then make
- if [ $TRAVIS_OS_NAME == osx ]; then make