language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
os:
- linux
- osx
before_install:
- echo $LANG
- echo $LC_ALL

script:
# this is needed to make osx use gcc instead of clang
- if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CC" = "gcc" ]; then export CXX=g++-4.8; fi

- if [ $TRAVIS_OS_NAME == linux ]; then make; fi
- if [ $TRAVIS_OS_NAME == osx ]; then make; fi

