language: cpp
sudo: required
dist: trusty
compiler:
# - clang # doesn't work yet; chokes on std::bad_alloc, see https://travis-ci.org/schnaader/fairytale/jobs/355305072
- gcc
os:
- linux
- osx
before_install:
- echo $LANG
- echo $LC_ALL
script:
- if [ $TRAVIS_OS_NAME == linux ]; then make; fi
- if [ $TRAVIS_OS_NAME == osx ]; then make; fi