language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
os:
- linux
- osx
osx_image: xcode8
before_install:
- echo $LANG
- echo $LC_ALL

before_install
# this is needed to make osx use gcc instead of clang
- if [ $TRAVIS_OS_NAME == osx ]; then export CXX=g++-4.9; fi

script:
- if [ $TRAVIS_OS_NAME == linux ]; then make; fi
- if [ $TRAVIS_OS_NAME == osx ]; then make; fi

